//auth action types
export const LOAD_PROFILE = "LOAD_PROFILE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOG_OUT = "LOG_OUT";


export const HOME_VIDEOS_SUCCESS="HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAILURE="HOME_VIDEOS_FAILURE";
export const HOME_VIDEOS_REQUEST="HOME_VIDEOS_REQUEST";